version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container2
    environment:
      MYSQL_DATABASE: prod_hms  
      MYSQL_USER: admin 
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    networks:
      - ola_network


  springboot:
    build: .
    container_name: hms_bc_app
    ports:
      - "9090:9090"
    depends_on:
      - mysql
    networks:
      - ola_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-bc-hms.cmcvusy1u2mz.us-east-2.rds.amazonaws.com:3306/prod_hms
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 12345678

networks:
  ola_network:
    driver: bridge
